### ISSUE TITLE
iOS 13 breaks Cancel button

### ISSUE THREAD

**Issue by mnidhk** [jtaubensee/SearchApp#2]
Hello John,

You helped me last time with previous issue. Hopefully you have an idea about this one.

Repro: I used the same project, which i used in my previous issue
[Searchproject](https://github.com/jtaubensee/SearchApp/files/3179991/SearchTest.zip)

After installing iOS13, the search functionality is behaving strange with the "Cancel" button.
- Click on search, type text etc. works
- But after using the "Cancel" button it kind of freezes/puts another sort of navigation layer on top of the current Navigation 
1) At this point, all the toolbar icons not working anymore.
2)Hamburger icon not working anymore
3)When clicking on detail of the list it navigate to the detail page but the NavigationBar shows 2 navigation bars on top of each other. The master and detail navigation icons and text.
4)When using "Large Titles", the title is not showing anymore in de NavigationBar when scrolling up the list/transformed to "Small Title"

Slide from left to right to the menu, choose another menu item and back to the list resets the search functionality and everything works again.
Tried different xamarin forms releases but even the latest has this issue. SO i don't know if this is a iOS13 or xamarin forms issue?!

The only workaround i have found is to set HidesNavigationBarDuringPresentation= true.
In this case the cancel button works ok and everything looks fine.
Hopefully you have an idea where to look for a solution?

Thanks in advance!

**Comment by mnidhk** [comment]
With latest ios13 the cancel button works like before so looks like it was an ios13 bug.
Like some other issues. Ios13 hasn't  the best software releases so far...

**Comment by jtaubensee** [comment]
Hi @mnidhk  - Sorry I missed your previous comment, but glad to hear you were able to figure out the root issue.
